import { type Transaction } from './types';

export const sampleTransactions: Transaction[] = [
  {
    id: '1',
    ticker: 'AAPL',
    companyName: 'Apple Inc.',
    type: 'BUY',
    shares: 10,
    price: 150.75,
    date: '2023-05-10',
    notes: 'Initial purchase',
  },
  {
    id: '2',
    ticker: 'GOOGL',
    companyName: 'Alphabet Inc.',
    type: 'BUY',
    shares: 5,
    price: 120.20,
    date: '2023-07-22',
    notes: 'Buy the dip',
  },
  {
    id: '3',
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    type: 'BUY',
    shares: 15,
    price: 250.00,
    date: '2023-01-15',
    notes: 'Long term hold',
  },
  {
    id: '4',
    ticker: 'NVDA',
    companyName: 'NVIDIA Corporation',
    type: 'BUY',
    shares: 15,
    price: 450.50,
    date: '2023-09-01',
    notes: 'AI boom',
  },
  {
    id: '5',
    ticker: 'TSLA',
    companyName: 'Tesla, Inc.',
    type: 'SELL',
    shares: 7,
    price: 280.00,
    date: '2023-10-05',
    notes: 'Take some profit',
  },
];
